---
kind: Template
apiVersion: v1
metadata:
  name: secret-store
  annotations:
    openshift.io/display-name: Arbitrary Secret Manager
    description: An example Template for catalog.
    tags: quickstart,secret
    iconClass: icon-sso
    openshift.io/long-description: |-
      Minimal example template to add templates as a catalog item to Openshift.
      Required:
        - openshift.io/* annotations.
        - 'iconClass' has to be 'icon-$' where '$' is the name of an image name from: https://github.com/openshift/origin-web-console/tree/enterprise-3.11/app/images/logos
    openshift.io/provider-display-name: theRemix
    openshift.io/documentation-url: https://github.com/theRemix/openshift-secret-store
    openshift.io/support-url: https://github.com/theRemix/openshift-secret-store/issues
    template.openshift.io/bindable: 'false'
message: |-
  The following service(s) have been created in your project: Secret ${NAME}
labels:
  template: secret-store
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}"
  stringData:
    key: "${KEY}"
    val: "${VAL}"
parameters:
- name: NAME
  displayName: Name
  description: Name of secret
  value: "my-secret"
  required: true
- name: KEY
  displayName: Key
  description: Key for secret
  required: true
  value: ""
- name: VAL
  displayName: Value
  description: Value for secret
  required: true
  value: ""
